apiVersion: charts.nginx.org/v1alpha1
kind: nginxIngress
metadata:
  name: nginxingress
  namespace: nginx-ingress
spec:
  controller:
    defaultTLS:
      secret: nginx-ingress/default-server-secret
    image:
      pullPolicy: IfNotPresent
      repository: nginx/nginx-ingress
      tag: "2.3.0"
    ingressClass: nginx
    kind: deployment
    nginxplus: false
    replicaCount: 1
    serviceAccount:
      imagePullSecretName: ""